import type { NextPage } from "next";
import Head from "next/head";
import { Home } from "../components";
import { Layout } from "../containers/Layout";

const MainPage: NextPage = () => {
    return (
        <div className="container">
            <Head>
                <title>Sinakhx Blog</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
            </Head>
            <Layout>
                <Home />
            </Layout>
        </div>
    );
};

export default MainPage;
