import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
    return (
        <div className="container">
            <Head>
                <title>Sinakhx Blog</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <span>Sinakhx Blog!</span>
                </h1>

                <p className={styles.description}>
                    Get started by joining us and creating a new post!
                </p>

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>Learn about Next.js in an interactive course with quizzes!</p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a href="https://github.com/Sinakhx" target="_blank" rel="noopener noreferrer">
                  Powered by &nbsp; <strong>Sina Khodabandehloo &copy; 2022</strong>
                </a>
            </footer>
        </div>
    );
};

export default Home;
